name: ReviewdogTest
on: [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Composer install
        uses: php-actions/composer@v2
        with:
          command: global require overtrue/phplint "squizlabs/php_codesniffer=*"
      - name: PWD
        run: pwd
      - name: PHPLint
        run: vendor/bin/phplint
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
      - name: Check reviewdog version
        run: reviewdog -version
#      - uses: hrysd/action-php_codesniffer@master
#        with:
#          github_token: ${{ secrets.github_token }}
#          standard: PSR12
#          target_directory: .
