name: reviewdog
on: [ pull_request ]

jobs:
  php_codesniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        run: reviewdog -version
      - uses: hrysd/action-php_codesniffer@master
        with:
          github_token: ${{ secrets.github_token }}
          standard: PSR12
          target_directory: .
